import { createDefaultWorld, distance } from "./domain/world.js";
import { loadWorld, saveWorld, resetWorld } from "./domain/persistence.js";
import { enterRoom } from "./domain/apartment.js";
import { getRoomCapabilities } from "./domain/room-capabilities.js";
import { createCityState } from "./domain/city.js";
import { layoutObjects, layoutPlaces } from "./domain/layout.js";
import { EugeneMessengerAdapter } from "./integration/eugene.js";
import { SymbiontEventAdapter } from "./integration/symbiont.js";
import { createEvent } from "./integration/event-envelope.js";
import { RealtimeWorld } from "./integration/realtime.js";

const canvas=document.querySelector("#world"),ctx=canvas.getContext("2d"),panel=document.querySelector("#panel"),title=document.querySelector("#panel-title"),desc=document.querySelector("#panel-description"),actions=document.querySelector("#panel-actions");
const world=loadWorld(createDefaultWorld());if(!world.apartment)world.apartment=createDefaultWorld().apartment;
const city=createCityState(),keys=new Set(),eugene=new EugeneMessengerAdapter(),symbiont=new SymbiontEventAdapter(),realtime=new RealtimeWorld({roomId:"apartment:demo",profile:{name:"Guest",avatar:"default"}});
let pointerId=null,lastMoveAt=0,lastNetworkMoveAt=0,scene="apartment",selectedPlace=null;
const labels={mailbox:"📮",laptop:"💻",tv:"📺",player:"🎵",wardrobe:"👕",door:"🚪",fridge:"🧊",menu:"🍽",phone:"📱",pantry:"🛒",books:"📚",mirror:"🪞",portal:"🌆"};
function resize(){const d=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(canvas.clientWidth*d);canvas.height=Math.round(canvas.clientHeight*d);ctx.setTransform(d,0,0,d,0,0)}addEventListener("resize",resize);resize();
function point(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}function moveToward(p){const dx=p.x-world.avatar.x,dy=p.y-world.avatar.y,l=Math.hypot(dx,dy);if(l<4)return;const s=Math.min(l,Math.max(2.5,Math.min(canvas.clientWidth,canvas.clientHeight)*.006));world.avatar.x=Math.max(45,Math.min(canvas.clientWidth-45,world.avatar.x+dx/l*s));world.avatar.y=Math.max(75,Math.min(canvas.clientHeight-45,world.avatar.y+dy/l*s))}
canvas.addEventListener("pointerdown",e=>{if(panel.hidden){pointerId=e.pointerId;canvas.setPointerCapture?.(pointerId)}e.preventDefault()},{passive:false});canvas.addEventListener("pointermove",e=>{if(e.pointerId!==pointerId)return;const n=performance.now();if(n-lastMoveAt>=16)moveToward(point(e));lastMoveAt=n;e.preventDefault()},{passive:false});canvas.addEventListener("pointerup",e=>{if(e.pointerId===pointerId){pointerId=null;saveWorld(world)}});canvas.addEventListener("pointercancel",()=>pointerId=null);
addEventListener("keydown",e=>{keys.add(e.key.toLowerCase());if(e.key.toLowerCase()==="e")interact();if(e.key==="Escape"){if(!panel.hidden)panel.hidden=true;else if(scene==="street")returnApartment();}});addEventListener("keyup",e=>keys.delete(e.key.toLowerCase()));
function objects(){return layoutObjects(world.objects,world.apartment.currentRoom,canvas.clientWidth,canvas.clientHeight)}function nearest(){let b=null,bd=Infinity;for(const o of objects()){const d=distance(world.avatar,o);if(d<o.r+28&&d<bd){b=o;bd=d}}return b}
function publish(type,payload={},context={}){symbiont.publish(createEvent(type,payload,{...context,worldId:"local-world",apartmentId:"local-apartment"}))}
function show(t,d,buttons=[]){title.textContent=t;desc.textContent=d;actions.innerHTML="";for(const [label,fn] of buttons){const b=document.createElement("button");b.textContent=label;b.onclick=fn;actions.appendChild(b)}panel.hidden=false}
function openWork(){show("💼 STNetwork","One employment identity, two interfaces.",[["Classic work interface",()=>location.href="src/classic/work.html"],["Employer directory",()=>location.href="src/classic/employer.html"],["Resume",()=>location.href="src/classic/work.html"]]);publish("employment.interface.opened")}
function openCity(){scene="street";panel.hidden=true;realtime.send("scene.change",{scene:"street"});publish("street.entered")}
function returnApartment(){scene="apartment";panel.hidden=true;realtime.send("scene.change",{scene:"apartment"});publish("apartment.entered")}
function openPlace(p){selectedPlace=p;const buttons=[];if(p.type==="employer"){buttons.push(["Enter company",()=>{publish("company.entered",{placeId:p.id});location.href="src/classic/company.html?id="+encodeURIComponent(p.id)}],["View vacancies",()=>{location.href="src/classic/work.html"}],["Contact via Eugene",()=>{publish("employer.contact.requested",{placeId:p.id});show("Eugene","Employer conversation requested.")}]);}else if(p.type==="education"){buttons.push(["Open learning",()=>show(p.name,p.description)]);}else{buttons.push(["Open service",()=>show(p.name,p.description)])}buttons.push(["Back to street",()=>{panel.hidden=true}]);show("🏢 "+p.name,p.description,buttons);publish("city.place.opened",{placeId:p.id,placeType:p.type})}
function interact(){if(scene==="street"){const p=layoutPlaces(city.places,canvas.clientWidth,canvas.clientHeight).find(p=>Math.hypot(p.x-world.avatar.x,p.y-world.avatar.y)<90);if(p)return openPlace(p);return}const o=nearest();if(!o){openRoomCapabilities();return}if(o.type==="portal"){openCity();return}const buttons=o.capabilities.map(c=>[c,()=>runCapability(o,c)]);buttons.push(["💼 STNetwork",openWork]);for(const u of realtime.users.values())buttons.push(["Invite "+(u.profile?.name||"user"),()=>realtime.invite(u.id)]);show((labels[o.type]||"◈")+" "+o.name,"A spatial capability.",buttons);publish("object.interacted",{}, {objectId:o.id})}
async function runCapability(o,c){if(c==="room.enter"){enterRoom(world.apartment,o.targetRoom);world.avatar.x=180;world.avatar.y=350;panel.hidden=true;saveWorld(world);publish("room.entered",{roomId:o.targetRoom},{objectId:o.id,capability:c});return}if(c==="employment"||c==="jobs"||c==="resume")return openWork();if(c==="message.read"||c==="message.compose"){await eugene.listConversations();show("Eugene Messenger","Eugene adapter boundary is ready; external transport is not configured.");return}if(c==="avatar.edit"){world.avatar.appearance.clothes=world.avatar.appearance.clothes==="casual"?"formal":"casual";saveWorld(world);show("👕 Avatar","Outfit changed to "+world.avatar.appearance.clothes);return}show((labels[o.type]||"◈")+" "+o.name,"Capability "+c+" is available at the integration boundary.");publish(c+".requested",{}, {objectId:o.id,capability:c})}
function openRoomCapabilities(){const r=getRoomCapabilities(world.apartment.currentRoom);if(!r)return;const buttons=r.capabilities.map(c=>[c.label,()=>{if(["employment","work","jobs","resume"].includes(c.id))openWork();else show("Capability",c.label)}]);buttons.push(["💼 STNetwork",openWork]);show("🏠 "+r.title,"Contextual capabilities for this room.",buttons)}
document.querySelector("#close-panel").onclick=()=>panel.hidden=true;document.querySelector("#save").onclick=()=>{const ok=saveWorld(world);document.querySelector("#status").textContent=ok?"Saved locally":"Save failed";};document.querySelector("#reset").onclick=()=>{resetWorld();location.reload()};
realtime.on(e=>{if(e.type==="realtime.status"){const s=e.status;document.querySelector("#status").textContent=s==="online"?"Online · "+(scene==="street"?"Street":world.apartment.currentRoom):(s==="connecting"?"Connecting…":"Offline · local mode");}if(e.type==="presence.invite")show("🏠 Invitation","You have been invited into "+e.payload.roomId+".",[["Accept",()=>{realtime.send("room.join",{roomId:e.payload.roomId,x:180,y:350,profile:{name:"Guest",avatar:"default"}});panel.hidden=true}]]);if(e.type==="interaction.proximity")show("Nearby interaction","Another user interacted nearby.")});realtime.connect(world.avatar);
function drawApartment(){const w=canvas.clientWidth,h=canvas.clientHeight;ctx.fillStyle="#26312b";ctx.fillRect(0,0,w,h);ctx.fillStyle="#35443a";ctx.fillRect(25,70,w-50,h-95);ctx.strokeStyle="#647268";ctx.lineWidth=3;ctx.strokeRect(25,70,w-50,h-95);ctx.fillStyle="#d6dfd7";ctx.font="18px system-ui";ctx.textAlign="left";ctx.fillText(world.apartment.rooms.find(r=>r.id===world.apartment.currentRoom)?.name||"Apartment",45,105);for(const o of objects()){const n=nearest()===o;ctx.fillStyle=n?"#e8d37a":"#9aa69c";ctx.beginPath();ctx.arc(o.x,o.y,n?o.r+6:o.r,0,Math.PI*2);ctx.fill();ctx.fillStyle="#172019";ctx.font="26px system-ui";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(labels[o.type]||"◈",o.x,o.y);ctx.font="12px system-ui";ctx.fillText(o.name,o.x,o.y+o.r+14)}}
function drawStreet(){const w=canvas.clientWidth,h=canvas.clientHeight;ctx.fillStyle="#202832";ctx.fillRect(0,0,w,h);ctx.fillStyle="#39424d";ctx.fillRect(0,h*.28,w,h*.45);ctx.fillStyle="#53606d";ctx.fillRect(0,h*.73,w,h*.27);ctx.fillStyle="#d9dde2";ctx.font="18px system-ui";ctx.textAlign="left";ctx.fillText("🌆 City Street",30,42);for(const p of layoutPlaces(city.places,canvas.clientWidth,canvas.clientHeight)){ctx.fillStyle=p.type==="employer"?"#c7a86a":p.type==="education"?"#8eb8d8":"#9aa69c";ctx.fillRect(p.x-48,p.y-35,96,70);ctx.fillStyle="#10151a";ctx.font="12px system-ui";ctx.textAlign="center";ctx.fillText(p.name,p.x,p.y+88)}}
function drawUsers(){for(const u of realtime.users.values()){ctx.fillStyle="#f1a6cf";ctx.beginPath();ctx.arc(u.x,u.y,18,0,Math.PI*2);ctx.fill();ctx.fillStyle="#eee";ctx.font="12px system-ui";ctx.textAlign="center";ctx.fillText(u.profile?.name||"Guest",u.x,u.y+34)}ctx.fillStyle="#b9d7ff";ctx.beginPath();ctx.arc(world.avatar.x,world.avatar.y,18,0,Math.PI*2);ctx.fill();ctx.fillStyle="#222";ctx.beginPath();ctx.arc(world.avatar.x,world.avatar.y-3,5,0,Math.PI*2);ctx.fill();ctx.fillStyle="#ddd";ctx.font="12px system-ui";ctx.textAlign="center";ctx.fillText("You",world.avatar.x,world.avatar.y+34)}
function draw(){ctx.clearRect(0,0,canvas.clientWidth,canvas.clientHeight);scene==="street"?drawStreet():drawApartment();drawUsers()}
function tick(){let dx=0,dy=0;if(keys.has("w")||keys.has("arrowup"))dy--;if(keys.has("s")||keys.has("arrowdown"))dy++;if(keys.has("a")||keys.has("arrowleft"))dx--;if(keys.has("d")||keys.has("arrowright"))dx++;if(dx||dy)moveToward({x:world.avatar.x+dx*100,y:world.avatar.y+dy*100});if(performance.now()-lastNetworkMoveAt>50){realtime.move(world.avatar.x,world.avatar.y);lastNetworkMoveAt=performance.now()}draw();requestAnimationFrame(tick)}tick();
